adds url param support to code and resources pages.
sveltejs/community-legacy pull request #100
Opened 2020-02-25 21:21 UTC by kevmodrome

* URL params are now updated when you select and unselect tags.
* Code and Resources pages now support linking directly to tags like so:

`.../resources?tag=official&tag=web+app+frameworks`

2020-02-25 21:21 UTC, sw-yx commented
Generating Deploy Preview! beep boop beep boop

Building with commit 018f7bd708257858943f89eeaab164f83e1f2f39

https://app.netlify.com/sites/svelte-community/deploys/5e558fdfce606d000bcc904c

2020-02-25 21:27 UTC, kevmodrome commented
This solves #25

2020-02-25 22:45 UTC, ryanatkn requested changes
Yay thank you, this is awesome! I was just wanting to link to a specific tag.

I saw one issue where the tags aren't updated when the tags are cleared. The fix I suggested (see inline comments) does leave a `?` in the address bar, might be easy to fix.

Another minor thing we can fix later is that it filters after mounting, so you get a flash of full content, which is no problem but could be polished. I'll probably look for a way to fix it if nobody beats me to it. I see no reason to fix in this PR unless that's what you'd prefer to do.

2020-02-25 22:45 UTC, ryanatkn commented on src/routes/code.svelte
>    const clearSelectedTags = () => {
In `clearSelectedTags` we want to call `updateUrl(selectedTags)` after reassigning `selectedTags = selectedTags;` like we do in `toggleTag`.

2020-02-25 22:45 UTC, ryanatkn commented on src/routes/resources.svelte
>    const clearSelectedTags = () => {
In `clearSelectedTags` we want to call `updateUrl(selectedTags)` after reassigning `selectedTags = selectedTags;` like we do in `toggleTag`.

2020-02-26 07:19 UTC, kevmodrome commented
Makes sense, i'll update that and push a new commit

2020-02-26 10:03 UTC, ryanatkn approved these changes

2020-02-26 10:04 UTC, merged