Add wetix logo
sveltejs/community-legacy pull request #352
Opened 2020-11-27 08:15 UTC by si3nloong

2020-11-27 08:15 UTC, sw-yx commented
Generating Deploy Preview! beep boop beep boop

Building with commit f26335b85ea3d2a96a4b5d3ea7d29f70a3b16ab6

https://app.netlify.com/sites/svelte-community/deploys/5fc0b594cc2c0f00085962a8

2020-12-23 10:40 UTC, si3nloong commented
Hi, any idea when is this going to merge?

2021-01-20 18:39 UTC, dreitzner requested changes
- [x] remove unused css class

everything else seems fine

2021-01-20 18:39 UTC, dreitzner commented on whos-using-svelte/WhosUsingSvelte.svelte
> +	<a target="_blank" rel="noopener" href="https://wetix.my" class="WeTix"><img src="organisations/wetix.svg" alt="WeTix" loading="lazy"/></a>
why use a class `.wetix` in `a`-tag

2021-01-22 07:03 UTC, si3nloong commented on whos-using-svelte/WhosUsingSvelte.svelte
> +	<a target="_blank" rel="noopener" href="https://wetix.my" class="WeTix"><img src="organisations/wetix.svg" alt="WeTix" loading="lazy"/></a>
done the fix. Can we deploy it very soon?

2021-01-22 20:21 UTC, dreitzner requested changes
@si3nloong please pull in the latest changes from master and add your info to https://github.com/sveltejs/community/blob/master/whos-using-svelte/WhosUsingSvelte.js

2021-05-13 03:55 UTC, benmccann commented on data/code.yml
> +  - name: '`svelte-reactive-form`'
components now live at https://github.com/svelte-society/sveltesociety.dev

2021-05-15 12:22 UTC, closed without merging