Added logo and a link
sveltejs/community-legacy pull request #379
Opened 2021-01-20 13:49 UTC by BraydenGirard

2021-01-20 13:49 UTC, sw-yx commented
:construction_worker: Generating Deploy Preview! beep boop beep boop


:hammer: Explore the source changes: f24a0fee4f33ba0b06bf077d6e8b0637ac28edb5

:mag: Inspect the deploy logs: [https://app.netlify.com/sites/svelte-community/deploys/600834db1a835a0007cd9752](https://app.netlify.com/sites/svelte-community/deploys/600834db1a835a0007cd9752?utm_source=github&utm_campaign=bot_dl)

2021-01-20 18:27 UTC, dreitzner requested changes
- [ ] fix png inside of svg

2021-01-20 18:27 UTC, dreitzner commented on whos-using-svelte/organisations/daydream.svg
> +        <image id="_Image41" width="41px" height="42px" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACkAAAAqCAYAAAAu9HJYAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAE0UlEQVRYhbWXzY9VNRjGn+d9j/8MM4zOE
is there a way to not use PNGs inside of your svg?

2021-01-21 18:18 UTC, BraydenGirard commented on whos-using-svelte/organisations/daydream.svg
> +        <image id="_Image41" width="41px" height="42px" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACkAAAAqCAYAAAAu9HJYAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAE0UlEQVRYhbWXzY9VNRjGn+d9j/8MM4zOE
I have tried to remove the png but I'm not sure if the source eps I am working from has it in it. Is this latest commit any better?  Sorry for confusion.

2021-01-22 20:24 UTC, dreitzner requested changes
please pull in the latest changes from master and add your info to https://github.com/sveltejs/community/blob/master/whos-using-svelte/WhosUsingSvelte.js

2021-01-25 14:03 UTC, BraydenGirard commented
Done!

2021-01-25 16:17 UTC, dreitzner reviewed
Looks good 👍

2021-01-25 16:17 UTC, dreitzner approved these changes

2021-01-26 08:14 UTC, merged