add smartnews logo
sveltejs/community-legacy pull request #410
Opened 2021-02-13 03:33 UTC by ianwith

2021-02-13 03:33 UTC, sw-yx commented
Generating Deploy Preview! beep boop beep boop

Building with commit ff030dd7303098115425568c499db78883698eca

https://app.netlify.com/sites/svelte-community/deploys/602748857250720007adb95c

2021-02-22 14:11 UTC, dreitzner requested changes

2021-02-22 14:11 UTC, dreitzner commented on whos-using-svelte/organisations/smartnews.svg
> +    <image xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAukAAALoCAYAAADFmGuuAAAEGWlDQ1BrQ0dDb2xvclNwYWNlR2VuZXJpY1JHQgAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc
Is it possible to export the svg without png images in them?
Or at least make it smaller than 105kB :)

2021-02-23 02:55 UTC, ianwith commented on whos-using-svelte/organisations/smartnews.svg
> +    <image xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAukAAALoCAYAAADFmGuuAAAEGWlDQ1BrQ0dDb2xvclNwYWNlR2VuZXJpY1JHQgAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc
@dreitzner Thank you!
I have compressed the SVG image to 102K. if it is still too big, I can try PNG format, which is about 12K.

2021-02-23 08:09 UTC, dreitzner commented on whos-using-svelte/organisations/smartnews.svg
> +    <image xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAukAAALoCAYAAADFmGuuAAAEGWlDQ1BrQ0dDb2xvclNwYWNlR2VuZXJpY1JHQgAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc
12kB sounds reasonable to me 👍

2021-02-24 01:04 UTC, ianwith commented on whos-using-svelte/organisations/smartnews.svg
> +    <image xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAukAAALoCAYAAADFmGuuAAAEGWlDQ1BrQ0dDb2xvclNwYWNlR2VuZXJpY1JHQgAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc
@dreitzner changed svg to png.

2021-02-24 01:07 UTC, ianwith commented on whos-using-svelte/organisations/smartnews.svg
> +    <image xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAukAAALoCAYAAADFmGuuAAAEGWlDQ1BrQ0dDb2xvclNwYWNlR2VuZXJpY1JHQgAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc
by the way, is it possible to make it prominent?

2021-02-24 18:20 UTC, dreitzner approved these changes

2021-02-24 18:20 UTC, dreitzner commented
LGTM

2021-03-16 15:34 UTC, ianwith commented
@dreitzner are you able to merge this PR? Thank you!

2021-03-17 18:12 UTC, merged