Adding GearID Geo Logo and entry into WhosUsingSvelte.js
sveltejs/community-legacy pull request #418
Opened 2021-03-09 03:59 UTC by mkamaalr

2021-03-09 04:00 UTC, sw-yx commented
Generating Deploy Preview! beep boop beep boop

Building with commit c2d76828b665ef54f20b873bf4cd3a80c36d9948

https://app.netlify.com/sites/svelte-community/deploys/6046f2bdf111d60007220b80

2021-03-17 18:18 UTC, dreitzner requested changes
- [ ] Please add trailing comma at the end of the list
- [ ] please add your entry add the end of the file
- [ ] please add your logo at max height of 72px or as svg

2021-03-18 08:03 UTC, mkamaalr reviewed
Deployed

2021-03-19 20:03 UTC, dreitzner requested changes

2021-03-19 20:03 UTC, dreitzner commented on whos-using-svelte/WhosUsingSvelte.js
> +  	{
There should be no changes here....

2021-03-20 06:36 UTC, dreitzner approved these changes
Lgtm

2021-04-12 18:40 UTC, dreitzner approved these changes

2021-04-14 19:01 UTC, merged