Added Svelte Vite Tailwind Template
sveltejs/community-legacy pull request #424
Opened 2021-03-22 17:24 UTC by Lukem121

2021-03-22 17:24 UTC, sw-yx commented
Generating Deploy Preview! beep boop beep boop

Building with commit 5511fa437da2c7a55693c62c652688b1b8a291f7

https://app.netlify.com/sites/svelte-community/deploys/6058d2ba0abf250007099ef7

2021-03-22 20:20 UTC, sw-yx commented on data/code.yml
> +	- name: '`svelte-vite-tailwind-template`'
![image](https://user-images.githubusercontent.com/6764957/112053264-198a2480-8b8f-11eb-9ae0-99bae8940674.png)

spaces not tabs

2021-03-22 20:20 UTC, sw-yx requested changes
spaces

2021-03-26 01:06 UTC, Lukem121 commented
I have removed the tabs and replaced with spaces, thanks.

2021-03-29 17:36 UTC, sw-yx approved these changes

2021-03-29 17:39 UTC, merged