Update WhoIsUsingSvelte
sveltejs/community-legacy pull request #447
Opened 2021-05-05 06:52 UTC by JulianvonGebhardi

Added our web project which is based on Svelte and Sapper.

2021-05-05 06:52 UTC, sw-yx commented
Generating Deploy Preview! beep boop beep boop

Building with commit 37071acb73b1704edd76b9dce5b3de82a9a99ea5

https://app.netlify.com/sites/svelte-community/deploys/609240ad7046810007cde8b3

2021-05-05 18:07 UTC, dreitzner requested changes

2021-05-05 18:07 UTC, dreitzner commented on whos-using-svelte/WhosUsingSvelte.js
> +	}
please add a trailing comma

2021-05-05 18:07 UTC, dreitzner commented on whos-using-svelte/WhosUsingSvelte.js
> +		src: "img/logo-color.svg",
- image is not there
- image name should resemble the company

2021-05-10 10:18 UTC, JulianvonGebhardi commented on whos-using-svelte/WhosUsingSvelte.js
> +	}
sorry, I just added it.

2021-05-10 10:19 UTC, JulianvonGebhardi commented on whos-using-svelte/WhosUsingSvelte.js
> +		src: "img/logo-color.svg",
ok, I just added the logo and committed the changes. Unfortunately I did on a different branch by accident. Sorry about that. I got a little confused by the interface since I only worked with Bitbucket so far.

2021-05-12 17:55 UTC, dreitzner commented on whos-using-svelte/WhosUsingSvelte.js
> +		src: "img/logo-color.svg",
I am sorry, but the logo sill does not show up.

2021-05-14 05:25 UTC, JulianvonGebhardi commented on whos-using-svelte/WhosUsingSvelte.js
> +		src: "img/logo-color.svg",
Sorry for the troube. It should work now!

2021-05-14 18:41 UTC, merged