Added the Fosshost
sveltejs/community-legacy pull request #453
Opened 2021-06-03 11:26 UTC by dragstor

2021-06-03 11:26 UTC, sw-yx commented
:construction_worker: Generating Deploy Preview! beep boop beep boop


:hammer: Explore the source changes: d82fe3753c442ca8f72c3a2af1e2872e447ed3e6

:mag: Inspect the deploy log: [https://app.netlify.com/sites/svelte-community/deploys/60b8bc6748683d0007787ca5](https://app.netlify.com/sites/svelte-community/deploys/60b8bc6748683d0007787ca5?utm_source=github&utm_campaign=bot_dl)

2021-06-03 14:38 UTC, sw-yx requested changes
could you explain what this svg does?

2021-06-03 14:38 UTC, sw-yx commented on whos-using-svelte/organisations/aarch64.svg
> +})({"ch":{"snap":false,"mono":false},"eq":[{"label":"master","gain":1},{"label":"64","f":64,"gain":0,"type":"peaking"},{"label":"32","f":32,"gain":0,"type":"lowshelf"},{"label":"125","f":125,"gain":0
wtf is this

2021-06-03 14:43 UTC, dragstor commented on whos-using-svelte/organisations/aarch64.svg
> +})({"ch":{"snap":false,"mono":false},"eq":[{"label":"master","gain":1},{"label":"64","f":64,"gain":0,"type":"peaking"},{"label":"32","f":32,"gain":0,"type":"lowshelf"},{"label":"125","f":125,"gain":0
It is a 100% fair question. 

That asset was provided by the ARM Computers recently.
I've removed the JS in question and will be pushing a fix in a second.

Thanks!!!

2021-06-03 14:45 UTC, dragstor commented
Pushed the fixed SVG for the aarch64 logo.

2021-06-18 19:38 UTC, benmccann commented
Thanks. However, we've decided just to feature the most prominent companies using Svelte on the homepage and are no longer featuring sites submitted by the community

2021-06-18 19:38 UTC, closed without merging